In [3]:
# numpy arrays methods 
import numpy as np
arr1=np.array([[3, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
np.min(arr1) # it will return the minimum value of the array


np.int64(2)

In [5]:
arr2=np.array([[3, 2, 3, 4, 5], [6, 7, 8, 9, 33]])
np.max(arr2) # it will return the maximum value of the array

np.int64(33)

In [7]:
arr3=np.array([[3, 2, 3, 4, 5], [6, 7, 8, 9, 33]])
print(arr3)
np.sum(arr3) # it will return the sum of all the elements in the array

[[ 3  2  3  4  5]
 [ 6  7  8  9 33]]


np.int64(80)

In [11]:
# now if we want the sum of the elements in each column we can use the axis parameter and set it to 0
# y-axis=0 means we want to sum the elements in each column
# x-axis=1 means we want to sum the elements in each row
sm=np.sum(arr3, axis=0) # it will return the sum of the elements in

print(sm)

smx = np.sum(arr3, axis=1) # it will return the sum of the elements in each row
print(smx)

[ 9  9 11 13 38]
[17 63]


In [16]:
# now mean 

arr3.mean() # it will return the mean of all the elements in the array

np.float64(8.0)

In [18]:
arr3.std() # it will return the standard deviation of all the elements in the array

np.float64(8.613942186943213)

In [19]:
arr3.argmax() # it will return the index of the maximum value in the array

np.int64(9)

In [20]:
arr3.argmin() # it will return the index of the minimum value in the array

np.int64(1)