In [5]:
import numpy as np
# Array Generation Function 
# range() function ! work like same in loop just we neet to write arange()

arr1=np.arange(1,10) # it will generate array from 1 to 9
arr1

arr2=np.arange(1,10,2) # it will generate array from 1 to 9 with step size of 2
arr2


array([1, 3, 5, 7, 9])

In [8]:
# We can also generate some Zeros and Ones array using numpy library.

arr3=np.zeros(5) # 

arr3   # this will generate 1D array with 5 Zeros (Vector form )




array([0., 0., 0., 0., 0.])

In [9]:
arr4=np.ones((3,3))
arr4  # this will generate 2D array with 3 rows and 3 columns with all values as 1 (Matrix form )


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# linspace() function is used to generate an array with evenly spaced values over a specified range.
arr5=np.linspace(1,5,2)# it will generate 2 values between 1 and 5 (including 1 and 5)
print(arr5)

arr6=np.linspace(1,5,3)
arr6

[1. 5.]


array([1., 3., 5.])